### ISSUE TITLE
Bug: Unable to update token 

### ISSUE THREAD

**Issue by ron-debajyoti** [interviewstreet/ghs#13]
Hi,  earlier I used the cli to generate the summary. Today I updated my token and tried to refresh/insert the new token but seems like the cli isn't accepting it. As a result the summary isn't generated
![backstage_bug](https://user-images.githubusercontent.com/22571664/162562545-c901d171-bd41-410e-9697-8e4bf6c2b3e8.png)

Also is the token stored as a variable ? I don't see any `.env` file here even to manually update my token :thinking:

**Comment by makkoncept** [comment]
Hi @ron-debajyoti, thank you for reporting this bug. This has been fixed. Now _ghs_ will prompt you for a token when you run `ghs -t` and if it's valid, the previous token will be overwritten by your new token.

A new release with this fix has been pushed to PyPI. Please update ghs by running `pip install ghs --upgrade`.

PS: the token is saved in `~/.ghs/ghs.config`. So you can also manually update it.

Let me know if you have any questions.

**Comment by ron-debajyoti** [comment]
Hey! Thanks for the quick fix and the clarification :smile:. It's working good now. Guess it's safe to close now.
