### ISSUE TITLE
There is no options to fill the Required scopes

### ISSUE THREAD

**Issue by jianwang-ntu** [interviewstreet/ghs#22]
Hi  
```
ghs -t 


Creating config file
please enter your github pat: [ghp_xxxxxxxxxxxxxxxxxxxx]
Error: The token does not have valid scopes.
 Required scopes: ['read:user', 'repo', 'read:packages'].
 Provided token scopes: ['repo']

```

I have granted the permission to the repo, however, on the GitHub setting page, there is not an option to make a read, how can I set this? 

A suggestion is that, may you  delete the judgment of read:* or make this optional

**Comment by makkoncept** [comment]
Hi @jianwang-ntu, please use this URL to create a new PAT https://github.com/settings/tokens/new?description=for_ghs&scopes=repo,read:user,read:packages

The scopes will be automatically selected using this link.
If this new PAT does not work, let me know.

**Comment by jianwang-ntu** [comment]
Thanks, @makkoncept.

nice answer, it works!
