### ISSUE TITLE
Error: Query failed with status code: 401

### ISSUE THREAD

**Issue by abhijhacodes** [interviewstreet/ghs#24]
I'm using this in Ubuntu 20.04
I've installed ghs using ```pip install ghs``` command and it's showing this error. I also tried using the source code and still shows the same error.
I used this last month and it worked fine, maybe it's because of the **Github Personal Access Token expired** or something else. Is there a way to **forget the user** so it asks for new Access Token (It didn't ask for it this time)
<br/>

![Screenshot from 2022-05-02 20-59-30](https://user-images.githubusercontent.com/77770628/166261706-b04ff388-dd14-434d-a52d-3ecff3bf087f.png)

**Comment by aaroosh-07** [comment]
@abhijhacodes You can update your GitHub PAT with the command `ghs -t <replace this with token>`

**Comment by abhijhacodes** [comment]
@aaroosh-07 Thanks it worked.
