### ISSUE TITLE
Documentation: activating virtual environment command for windows not working on powershell

### ISSUE THREAD

**Issue by arpit456jain** [interviewstreet/ghs#6]
it should be

  py -m venv env
.\env\Scripts\activate

**Comment by makkoncept** [comment]
Screenshot

![image](https://user-images.githubusercontent.com/34679965/161994691-ebe4fe6c-0ea0-4cf0-a54a-1ee739885a8c.png)

**Comment by arpit456jain** [comment]
@makkoncept but its not working in powershell

![image](https://user-images.githubusercontent.com/55352601/162003683-de6e39c6-68a3-477d-ac3d-d5450c7b6ac8.png)

**Comment by arpit456jain** [comment]
.\env\Scripts\activate 
this will work in all shells

**Comment by makkoncept** [comment]
Gotha. I was testing on cmd. Would you be interested in submitting a PR for this change in the README? @arpit456jain

**Comment by Rohit484** [comment]
Done
